
<?php echo $this->getForm(); ?>

<script type="text/javascript">
    
//    jQuery(function($){
//        $(document).ready(function() {
//            $('#frm_edit_add').submit(function() {
//                $('.validation-failed').addClass('control-group error');
//            });
//        })
//    });
    
    //< ![CDATA[
    var customForm = new VarienForm('frm_edit_add');
    //]]>
    function onCategoryChange(fieldset_selector, category_selector)
    { 
        //jQuery(function($){
            //$.colorbox({escKey: false, overlayClose: false, transition: "none", opacity: 0.8, href:'<?php echo $this->getSkinUrl('classifieds/images/ajax-loader.gif') ?>'});
       // });
        
        var to_rm_selector = '*[id^="' + fieldset_selector + '_"]';
        $$(to_rm_selector).each(function(el){
            
            var parent = $(el).up('div');
            parent.remove();
            //            el.getParent().remove();
            //            el.remove();
        });

        var params = {};
        params.parent_id = $(category_selector).getValue();
        
        var reloadurl = '<?php echo $this->getUrl('ads/item/edit') ?>';
        //Element.show('loadingmask');
        new Ajax.Request(reloadurl, {
            method: 'post',
            parameters: params,
            onComplete: function(transport) {
            
//                jQuery(function($){
//                    $.colorbox.close();
//                });
                //Element.hide('loadingmask');
                //$('output-div').innerHTML = "";
                //$('output-div').innerHTML = transport.responseText;
                $('frm_edit_add').insert({bottom: transport.responseText});
                
    //< ![CDATA[
    var customForm = new VarienForm('frm_edit_add');
    //]]>
            }
        });
    }
</script>
