<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="container">
            <div class="row">
                <div class="span12">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <div class="row">
                        <div class="span12">                    
                            <?php echo $this->getChildHtml('global_messages') ?>
                        </div>
                        <div class="span4">
                            <?php echo $this->getChildHtml('left') ?>
                        </div>
                        <div class="span8">
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span12">
                            <?php echo $this->getChildHtml('footer') ?>
                            <?php echo $this->getChildHtml('before_body_end') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
