<?php
$fieldset = $this->getFieldset();
$fieldsetType = $this->getType();
?>
<div class="row">
    <div class="span9">
        <fieldset id="<?php echo $fieldset->getHtmlId(); ?>" <?php echo $fieldset->serialize(array('class')); ?>>
            <?php if ($fieldsetType && $fieldsetType == 'attributes_fieldset'): ?>

                <?php
                $groups = $this->getAttributeSetGroups($fieldset);
                if ($groups == false) {
                    return;
                }

                $usedAtrGroupIds = $fieldset->getUsedAttributeGroupIds();
                ?>

                <?php foreach ($groups as $group): ?>
                    <?php if (in_array($group->getId(), $usedAtrGroupIds) !=true) {
                        continue;
                    } ?>
                    <div class="row">
                        <div class="span9">
                            <div class="well">
                                <?php echo $group->getAttributeGroupName() ?>
                                    <?php $rows = $this->getFieldsetElementsRowsColumns($fieldset, $group->getId()); ?>
                                    <?php if (isset($rows['multicol']) && count($rows['multicol']) > 0): ?>
                                    <div class="row">
                                            <?php $columns = $rows['multicol']; ?>
                                            <?php foreach ($columns as $col): ?>
                                            <div class="span3">
                                                <?php $elementsInCol = $col['element']; ?>
                                                <?php foreach ($elementsInCol as $element): ?>
                                                    <?php
                                                    if ($element->getType() != 'fieldset') {
                                                        echo $element->toHtml();
                                                    }
                                                    ?>
                                            <?php endforeach; ?>
                                            </div>
                                    <?php endforeach; ?>
                                    </div>
        <?php endif; ?>
                                        <?php if (isset($rows['singlecol']) && count($rows['singlecol']) > 0): ?>
                                    <div class="row">
                                        <div class="span9">
                                            <?php $elements = $rows['singlecol']; ?>
                                            <?php foreach ($elements as $element): ?>
                <?php echo $element->toHtml(); ?>
                                    <?php endforeach; ?>
                                        </div>
                                    </div>
        <?php endif; ?>
                                        <?php if (isset($rows['other']) && count($rows['other']) > 0): ?>
                                    <div class="row">
                                        <div class="span9">
                                            <?php $elements = $rows['other']; ?>
                                            <?php foreach ($elements as $element): ?>
                <?php echo $element->toHtml(); ?>
                                    <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>

                                        <?php if (isset($rows['button']) && count($rows['button']) > 0): ?>
                                    <div class="row">
                                        <div class="span9">
                                            <?php $elements = $rows['button']; ?>
                                            <?php foreach ($elements as $element): ?>
                <?php echo $element->toHtml(); ?>
                                    <?php endforeach; ?>
                                        </div>
                                    </div>
        <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>

            <?php else: ?>
    <?php echo $fieldset->getChildrenHtml(); ?>
<?php endif; ?>

        </fieldset>
    </div>
</div>
<?php $fieldset->getAfterElementHtml(); ?>
